VERSION_MAJOR = 0
VERSION_MINOR = 0
VERSION_BUILD = 2
VERSION_INFO = (VERSION_MAJOR, VERSION_MINOR, VERSION_BUILD)
VERSION_STRING = "%d.%d.%d" % VERSION_INFO
AUTHOR_NAME = "Sadovoy Alexey"
DESCRIPTION = "Temporary fix for swagger in Flask-AppBuilder"
AUTHOR_EMAIL = "lexisstv@yandex.ru"

__version__ = VERSION_INFO

